export const CONNECT_SCENE = 'CONNECT_SCENE';
export const MY_BOXES_SCENE = 'MY_BOXES_SCENE';
export const SIGN_UP_SCENE = 'SIGN_UP_SCENE';
export const SIGN_IN_SCENE = 'SIGN_IN_SCENE';
export const SELECTED_BOX_SCENE = 'SELECTED_BOX_SCENE';
